### ISSUE TITLE
Doesn't work with YouTube material layout

### ISSUE THREAD

**Issue by Keith94** [StoyanDimitrov/middle-mouse-button-scroll#1]
Great add-on!

One issue: with YouTube's [material layout](https://www.youtube.com/new) turned on, the add-on stops working on youtube.com.

I'm using version 0.0.1 because 0.0.2 was reported to be corrupt.

**Comment by StoyanDimitrov** [comment]
Hey, great to hear!
This is a general shortcoming of the current implementation that I'm willing to overcome. Unfortunately, I forgot to mention it in the description.

P.S. I've just resent the add-on for review to fix the corruption.

**Comment by Keith94** [comment]
Thanks for the fast reply. :)

I noticed the add-on also wasn't working inside some scrollable elements like here: https://en.wikipedia.org/w/index.php?title=Cave_Story&action=edit
You could also mention that it doesn't work on addons.mozilla.org. Or the `file://` and `moz-extension://` protocols.

Off topic: Is it possible to make the cursor locked in the same place while scrolling? Also right now I think the cursor moves a bit slower than the actual page's scroll bar (not 1:1 movement)?

**Comment by StoyanDimitrov** [comment]
The problem you describe is basically the same as the YouTube one and will be fixed with this issue.

No add-on work on several of mozilla.org websites for now. There's a [Bugzilla issue](https://bugzil.la/1295324) describing the reasons.

Right now there is a ratio of 0.8:1 (mouse movement to page scroll) so one can click on the upper part (assuming downward scroll) of the page and still be able to scroll down to the very bottom or at least very close to it. If the ratio were 1:1 you have to aim the click to the very top of the page which I find inconvenient since there are other parts of the browser chrome: search bar, address bar, add-on bar, bookmarks bar etc. This way if you click at the top 10% of the page heigh you are guaranteed to scroll to the bottom. Still, if you find this inconvenient file a separate issue. Please do the same for the cursor locking request.

**Comment by Keith94** [comment]
Good point! Your explanation makes sense. I will file a separate issue for the cursor locking. :)

**Comment by Keith94** [comment]
Btw, I noticed when a webpage didn't finish loading completely and you try to scroll, the add-on doesn't work at that point (only uses regular autoscrolling). Is that a separate issue or can it be fixed?

**Comment by StoyanDimitrov** [comment]
Good catch! It surely can be fixed.

**Comment by Keith94** [comment]
Is this abandoned?

**Comment by StoyanDimitrov** [comment]
The add-on is not abandoned. The issue fell off my radar.
